# backend/app/db/migrations/versions/68a9d8e37b59_init_schema.py
"""init schema

Revision ID: 68a9d8e37b59
Revises: 
Create Date: 2026-03-04 14:56:57.474370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '68a9d8e37b59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('physical_tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_code')
    )
    op.create_table('table_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('OPEN', 'BILL_REQUESTED', 'PAID', 'CLOSED')", name='table_group_state_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_print_events',
    sa.Column('table_group_id', sa.UUID(), nullable=False),
    sa.Column('printed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('printed_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['table_group_id'], ['table_groups.id'], ),
    sa.PrimaryKeyConstraint('table_group_id', 'printed_at')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_group_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('CONFIRMED')", name='order_state_check'),
    sa.ForeignKeyConstraint(['table_group_id'], ['table_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_group_tables',
    sa.Column('table_group_id', sa.UUID(), nullable=False),
    sa.Column('physical_table_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['physical_table_id'], ['physical_tables.id'], ),
    sa.ForeignKeyConstraint(['table_group_id'], ['table_groups.id'], ),
    sa.PrimaryKeyConstraint('table_group_id', 'physical_table_id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('physical_table_id', sa.UUID(), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=True),
    sa.Column('menu_item_name_snap', sa.String(length=200), nullable=False),
    sa.Column('unit_price_snap', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE', 'VOIDED')", name='order_item_state_check'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['physical_table_id'], ['physical_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_adjustments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_group_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference_order_item_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('WAIVER', 'MANUAL')", name='bill_adj_category_check'),
    sa.ForeignKeyConstraint(['reference_order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['table_group_id'], ['table_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_item_printing',
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('printed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('printed_by', sa.String(length=50), nullable=False),
    sa.Column('print_type', sa.String(length=20), nullable=False),
    sa.CheckConstraint("print_type IN ('ORIGINAL', 'DUPLICATE')", name='order_item_print_type_check'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('order_item_id', 'printed_at')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item_printing')
    op.drop_table('bill_adjustments')
    op.drop_table('order_items')
    op.drop_table('table_group_tables')
    op.drop_table('orders')
    op.drop_table('bill_print_events')
    op.drop_table('table_groups')
    op.drop_table('physical_tables')
    # ### end Alembic commands ###
